#!/bin/sh
### BEGIN INIT INFO
# Provides:          mount_ocfs2
# Required-Start:    drbd
# Required-Stop:     drbd
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Mount the ocfs2/drbd mount
### END INIT INFO

case "$1" in
    start)
	/bin/mount /dev/drbd1  <%= location %>
	;;
    stop)
    	/bin/umount <%= location %>
	;;
esac
