#!/usr/bin/env python
"""
This script replaces the live Icinga config with a different config.

REQUIREMENTS
This script requires python-argparse and is meant to be run on *nix-systems.

COPYRIGHT
Copyright 2012 - Kumina B.V./Rutger Spiertz (rutger@kumina.nl), this script is licensed under the GNU GPL version 3 or higher.

"""
#Import the classes needed
import argparse
from os import path
import os
import MySQLdb
import sys
import shutil

parser = argparse.ArgumentParser(description='This script replaces the live Icinga config with a different config.')
parser.add_argument('-c', '--configdir', action='store', default='/etc/icinga/config', help='The directory the Icinga config is in.')

# Script starts here...
args = parser.parse_args()

basedir = '/tmp/icinga'

if path.isfile(basedir):
    print 'Base dir ' + basedir + ' is a file, not replacing config.'
    sys.exit(1)
elif path.isfile(args.configdir):
    print 'Config dir ' + basedir + ' is a file, not replacing config.'
    sys.exit(1)
else:
    if path.isdir(args.configdir):
        shutil.rmtree(args.configdir)
    try:
        shutil.copytree(basedir, args.configdir)
    except OSError:
        print 'Error copying config.'
        sys.exit(1)
